### PR TITLE
add support for base64 encoded kong license data

### PR DESCRIPTION
**Pull request by usrbinkat**
Proposal for adding base64 encoded kong license data support #468

### CODE REVIEW

**Review by gszr — COMMENTED** [review]
This looks good to me! Thanks @usrbinkat.

Could you please rebase onto latest master so tests run?

**Comment by Tieske** [comment]
Should we be adding it here? in the docker images? Wouldn't it make more sense to do this in Kong itself?

**Comment by Tieske** [comment]
had a quick look; this function https://github.com/Kong/kong-ee/blob/next/2.4.x.x/kong/enterprise_edition/license_helpers.lua#L41-L92 gets the license data. If we just try b64-decode before returning it, return the decoded result, or if the decode fails, return the input. That should be backward compatible, and work across all distributions, not just Docker.

**Comment by bungle** [comment]
This adds full base64 and base64url support to Kong directly:
https://github.com/Kong/kong/pull/9379

which is about to be merged here:
https://github.com/Kong/kong/pull/9253

**Comment by usrbinkat** [comment]
Closing in favor of https://github.com/Kong/kong/pull/9379

**Pull request closed without merging**
