### PR TITLE
added tini for the dockerfiles

### PR DESCRIPTION
**Pull request by srinidhis05**
The fix to use dumb init / tini as a lite init system was added in [https://github.com/Kong/docker-kong/pull/48](https://github.com/Kong/docker-kong/pull/48), but seem to have missed in the docker files that are present currently. 
The PR is to add tini as a init system for the dockerfiles .
Ref: 
[docker-and-the-pid-1-zombie-reaping-problem]( https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/.)

### CODE REVIEW

**Comment by Abhishekvrshny** [comment]
cc: @hutchic

**Comment by Abhishekvrshny** [comment]
@hutchic The `go-pluginserver` can be a different image, which can be deployed as a sidecar, daemon set or as a standalone deployment. The `go-pluginserver` can again be spawned under tini in this case as `systemd` would not be supported in a normal docker container.

**Comment by hutchic** [comment]
Agreed it can be done that route, just discussing if we will go that route. If we did I don't think we'd go include `tini`.

Are there strong reasons I'm not seeing to use `tini`? My impression is it's a light process management tool to avoid zombies. So long as one can validate kong's healthiness / readiness process management kind of falls on the orchestration layer and arguably none of it should be done within the docker image itself

**Comment by Tieske** [comment]
@hutchic any update on this?

**Comment by hutchic** [comment]
I don't believe it benefits us / isn't widely asked for. I think we can close and folks that wish to use tini can build a container `FROM kong` or if demand does increase we can make the change

**Comment by Tieske** [comment]
ok, let's close for now.

**Pull request closed without merging**
