### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dmirgaleev**
Typo fix

### CODE REVIEW

**Comment by Tieske** [comment]
this is not a typo. the `compose` command was added to `docker` to replace the separate `docker-compose`.

If `docker compose --help` doesn't work for you, then update docker to a more recent version.

**Comment by gszr** [comment]
> If docker compose --help doesn't work for you, then update docker to a more recent version.

Specifically, the Kong compose requires:
```
Note The Kong Docker Compose file uses the v3.9 compose schema; as such, it requires Docker Engine version 20.10.0+.
```

**Comment by dmirgaleev** [comment]
Thank you for the clarification! I have `Docker version 20.10.17, build 100c701`. 
`docker compose` doesn't have the `--profile` flag, `docker-compose` has. That's why I thought it's a typo.
And when I try `KONG_DATABASE=postgres docker compose --profile database up -d`, I'm facing the `unknown flag: --profile` error.

**Comment by Tieske** [comment]
ok, but then the fix should be to do something that removes the --profile flag I guess?

**Comment by gszr** [comment]
What version does `docker compose version` print?

> Thank you for the clarification! I have `Docker version 20.10.17, build 100c701`. `docker compose` doesn't have the `--profile` flag, `docker-compose` has. That's why I thought it's a typo. And when I try `KONG_DATABASE=postgres docker compose --profile database up -d`, I'm facing the `unknown flag: --profile` error.

**Comment by gszr** [comment]
Mine:
```
$ docker --version
Docker version 20.10.23, build 7155243
$ docker compose version
Docker Compose version v2.15.1
$ docker compose --profile database up -d
[+] Running 0/0
 ⠋ Container compose-kong-1                Creating                                                                                                                                                  0.0s
 ⠋ Container compose-kong-migrations-1     Creating                                                                                                                                                  0.0s
 ⠋ Container compose-kong-migrations-up-1  Creating 
```

**Comment by dmirgaleev** [comment]
Thank you for your help, I've figured that out. To make it work, you also need the `docker-compose-plugin': https://docs.docker.com/compose/install/linux/#install-using-the-repository.

**Pull request closed without merging**
