### PR TITLE
add  KONG_CLUSTER_CERT and KONG_CLUSTER_CERT_KEY value

### PR DESCRIPTION
**Pull request by mrwanny**
Add support to configure KONG_CLUSTER_CERT and KONG_CLUSTER_CERT_KEY value via environment variables

### CODE REVIEW

**Comment by hbagdi** [comment]
I think we should certainly add support for something like this to Kong - it has been long overdue.
As coincidently, I spent some time yesterday doing this exactly: https://github.com/hbagdi/fly-kong/commit/4f0cf91dfac9a2879efebd20dc6ddaf380df7d2a.

But, this is the wrong place for it.
We should add this into kong/kong itself so that all platforms get it instead of docker itself.

If we were to merge this, it would be the first instance of "docker kong has additional KONG_ that other setups don't" where other setups are non-docker based deployments of Kong. And that goes against Kong's principle of running everywhere and anywhere.

**Comment by hbagdi** [comment]
xref https://github.com/Kong/kong/pull/9253

**Review by hutchic — CHANGES_REQUESTED** [review]
what @hbagdi said :)

**Comment by Tieske** [comment]
related #469

**Comment by mrwanny** [comment]
Closing, looking forward to https://github.com/Kong/docker-kong/pull/469

**Pull request closed without merging**
