### PR TITLE
release(2.8.4): release 2.8.4

### PR DESCRIPTION
**Pull request by AndyZhang0707**

### CODE REVIEW

**Comment by danielpoonwj** [comment]
hello! can i check when this docker image can be expected to be published? 2.8.4 fixes a bug we're facing and we would like to upgrade

**Comment by curiositycasualty** [comment]
@danielpoonwj shortly, within the next half-hour.

**Comment by curiositycasualty** [comment]
@danielpoonwj that is, I should have this merged within the next 15 minutes. I have no idea how long it'll take for the official image to arrive in the docker library.
That said, these versions are available now as https://hub.docker.com/r/kong/kong/tags?page=1&name=2.8

**Comment by curiositycasualty** [comment]
Official docker library PR opened: https://github.com/docker-library/official-images/pull/15473

**Pull request merged**
