### PR TITLE
curl installation in kong image.

### PR DESCRIPTION
**Pull request by etsrepo**
curl command is not present in latest kong image.

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Yes, I'm all for it. I use curl for health checking. 👍

**Comment by etsrepo** [comment]
this fixes issue https://github.com/Kong/docker-kong/issues/151

**Comment by chenglx** [comment]
I got the same issue and fix this this file in local as well.
Just not sure as base kong alpine image, should we include curl there?

**Comment by etsrepo** [comment]
@chenglx including there will help other images as well

**Comment by salazar** [comment]
We've just merged #154. Closing this. Thank you for contributing!

**Pull request closed without merging**
