### PR TITLE
chore(ownership) after-install now handles file / directory ownership

### PR DESCRIPTION
**Pull request by hutchic**
do not merge until after 2.2.0

### CODE REVIEW

**Review by murillopaula — APPROVED** [review]

**Comment by murillopaula** [comment]
fixed the syntax errors

not sure why the swarm tests are failing

but taking a quick look at the tests, we have some hardcoded versions:
- https://github.com/Kong/docker-kong/blob/chore/directory-ownership/tests/01-image.test.sh#L33
- https://github.com/Kong/docker-kong/blob/chore/directory-ownership/tests/01-image.test.sh#L113

this file for example is not defaulting `KONG_USER` to `kong` https://raw.githubusercontent.com/Kong/docker-kong/1.5.0/swarm/docker-compose.yml

🤔

but this one is: https://raw.githubusercontent.com/Kong/docker-kong/2.2.0/compose/docker-compose.yml 

need to investigate

**Comment by murillopaula** [comment]
@hutchic

**Comment by murillopaula** [comment]
@gszr

**Comment by murillopaula** [comment]
@hutchic @gszr please review it again

docker still needs the `chown -R kong:0 /usr/local/kong` and `chown kong:0 /usr/local/bin/kong` so we can run Kong as the overridden 1001 user (openshift)

https://github.com/Kong/docker-kong/pull/423/commits/99cba2fee6151dd40c7670055170cf9b9fbc5b2d

**Comment by hutchic** [comment]
the one hardcoded version fix is up for PR https://github.com/Kong/docker-kong/pull/420

**Comment by murillopaula** [comment]
@hutchic ok, but I think this is ready to be merged.. will fix/avoid the docker library complains and concerns about our current Dockerfile: https://github.com/docker-library/official-images/pull/8972

**Review by gszr — APPROVED** [review]

**Pull request merged**
