### PR TITLE
(docfix) minor README change to address latest updates

### PR DESCRIPTION
**Pull request by GGabriele**
Hello! This is just a minor doc fix to address changes in `compose` logic introduced with https://github.com/Kong/docker-kong/pull/493

### CODE REVIEW

**Comment by Tieske** [comment]
since this is about docker-compose, we should keep the instructions based on docker-compose, not on the makefile imo. I assume the makefile is mostly used for testing.

wdyt @hutchic ?

**Comment by GGabriele** [comment]
Hi @Tieske, thanks for having a look at this!

In my opinion, the advantage of using a makefile is to abstract certain operations for the users who will only know the specific make targets: next time something change in the `docker-compose.yaml` file (e.g. new flags, new db supported etc), nothing will change on the setup instructions.

Also, `make kong-dbless` clearly states what the end setup would look like, instead of an obscure `docker-compose up -d` , especially if different setups are supported, like in this case.

Obviously, just my 2 cents, up to you! :)

**Comment by kenmasumitsu** [comment]
> # How to use this template
> 
> This Docker Compose template provisions a Kong container with a Postgres database, plus a nginx load-balancer. After running the template, the `nginx-lb` load-balancer will be the entrypoint to Kong.
> 
> To run this template execute:
> 
> ```shell
> $ docker-compose up
> ```
> 
> 

The description is not true. Because Kong run as dbless mode.

I have no option to use `docker compose` or 'make`, could you write down correct description.

If `docker compose` is preferred, 
```
COMPOSE_PROFILES=database KONG_DATABASE=postgres docker-compose up -d
```

or, if `make` is preferred,
```
make kong-postgres
```

**Review by kikito — CHANGES_REQUESTED** [review]
Please change this so that:

* docker-compose is shown first and prioritarily (since it is what will be used in production)
* the makefile is mentioned as a secondary/development aid.

**Comment by gszr** [comment]
Superseded by #628.

**Pull request closed without merging**
